config/routes.rb
Rails.application.routes.draw do
  
  
  resources :links
  resources :messages do
    member do
      put "like" => "messages#upvote"
      put "unlike" => "messages#downvote"
    end
  end
  mount Commontator::Engine => '/commontator'
  resources :followers
  resources :followeds
  resources :canals
  resources :preferencia

  resources :usuarios, as: :users, only: [:show,:update]  #esto es una prueba, que si funciono 

  resources :relationships, only: [:create,:update,:index]

 
  resources :editlandings
  resources :pais
  get '/index', to: 'landing#index'
  get '/informacion', to: 'landing#informacion'
  get '/perfil', to: 'dashboard#profile'


  #administrar landing 
  get '/landingpage', to: 'editlandings#index'
  #administrar landing



  root 'dashboard#index'
   
  devise_for :users, controllers: { sessions: "users/sessions", :registrations => "users/registrations", :confirmations => "users/confirmations" }
   match '/users/:id/canals/:id', controller: 'canals', action: 'update', via: 'post'
          
  resources :users do
     resources :favoritos
  	 resources :canals do

       

     end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/asd.rb
class Asd < ApplicationRecord
end

app/models/canal.rb
class Canal < ApplicationRecord
	belongs_to :user
	has_many :messages
end

app/models/editlanding.rb
class Editlanding < ApplicationRecord
	dragonfly_accessor :banner
	dragonfly_accessor :imagenseccion2
	dragonfly_accessor :bannernewsletter
	
end

app/models/favorito.rb
class Favorito < ApplicationRecord
	belongs_to :user
	has_one :preferencium
end

app/models/followed.rb
class Followed < ApplicationRecord
end

app/models/follower.rb
class Follower < ApplicationRecord
end

app/models/link.rb
class Link < ApplicationRecord
	acts_as_commontable
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	belongs_to :canal
	dragonfly_accessor :archivo
	acts_as_votable
	acts_as_commontable
end

app/models/pai.rb
class Pai < ApplicationRecord
end

app/models/preferencium.rb
class Preferencium < ApplicationRecord
	has_one:favorito
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	include AASM

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, uniqueness: {scope: :followed_id}

  #validates :follower, presence: true
  #validates :followed, presence: true

  def self.relations?(follower,followed)
  	Relationship.where(follower:follower,followed:followed)
  				.or(Relationship.where(follower:followed,followed:follower))
  				.any?
  end

  def self.pending_for_user(follower)
  	Relationship.pending.where(followed: follower)
  end

	aasm column: "status" do 
	 	state :pending
	 	state :active, initial: true
	 	state :denied

	 	event :accepted do
	 		transitions from: [:pending], to: [:active]
	 	end

	 	event :rejected do
	 		transitions from: [:pending,:active], to: [:denied]
	 	end
	 end
end

app/models/user.rb
 require "httparty"
 require "json"
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 
  include HTTParty
 acts_as_commontator
 acts_as_voter

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  dragonfly_accessor :fotoperfil
  dragonfly_accessor :portada

  has_many :canals
  has_many :messages
  has_many :favoritos
 
  has_many :relationships
#  has_many :active_relationships, class_name:  "relationship",
#                                  foreign_key: "follower_id",
 #                                 dependent:   :destroy

 # has_many :passive_relationships, class_name:  "relationship",
  #                                 foreign_key: "followed_id",
   #                                dependent:   :destroy
  
  #has_many :following, through: :active_relationships, source: :followed

  #has_many :followers, through: :passive_relationships, source: :follower
  def follow?(followed)
    Relationship.relations?(self,followed)
  end


    # Follows a user.
  #def follow(other_user)
   # following << other_user
  #end

  # Unfollows a user.
  #def unfollow(other_user)
   # following.delete(other_user)
  #end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
    def self.abc

  	@json = get("http://localhost:4040/graduateds.json")
  	@json = @json.to_json
  	@parsed_json = ActiveSupport::JSON.decode(@json)
  	@no = @parsed_json

  	return @no

  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	@messages = Message.all
  end

  def profile

  end

  def blog

  end
end

app/helpers/canals_helper.rb
module CanalsHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pais_helper.rb
module PaisHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/blog.html.erb
<!-- BEGIN CONTENT-->
			<div id="content">
				<section>
					<div class="section-header">
						<ol class="breadcrumb">
							<li class="active">Blog masonry</li>
						</ol>
					</div>
					<div class="section-body">
						<div class="row">
							<div class="col-lg-12">

								<!-- BEGIN BLOG MASONRY -->
								<div class="card card-type-blog-masonry style-default-bright">
									<div class="row">
										<div class="col-md-3">
											<article>
												<div class="card-body style-default-dark text-center">
													<h3><i class="fa fa-quote-left"></i> Some quote <i class="fa fa-quote-right"></i></h3>
												</div>
												<div class="card-body blog-text">
													<div class="opacity-50">Posted on Feb 20 by <a href="#">Admin</a> | <a href="#">2 comments <i class="fa fa-comment-o"></i></a></div>
													<h4><a class="link-default" href="../../../html/pages/blog/post.html">Consectetur adipisicing elit</a></h4>
													<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.</p>
												</div>
											</article><!-- end /article -->
											<article>
												<div class="blog-image">
													<img src="<%= asset_path 'img2.jpg' %>" alt="" />
												</div>
												<div class="card-body blog-text">
													<div class="opacity-50">Posted on Feb 20 by <a href="#">Admin</a> | <a href="#">2 comments <i class="fa fa-comment-o"></i></a></div>
													<h3><a class="link-default" href="../../../html/pages/blog/post.html">Cupidatat non proident</a></h3>
													<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
													<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
												</div>
											</article><!-- end /article -->
											<article>
												<div class="card-body style-primary-light">
													<div class="opacity-75">Posted on Feb 20 by <a href="#">Admin</a> | <a href="#">2 comments <i class="fa fa-comment-o"></i></a></div>
													<h3><a class="link-default" href="../../../html/pages/blog/post.html">Cupidatat non proident</a></h3>
													<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
													<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
												</div>
											</article><!-- end /article -->
										</div><!--end .col -->
										<div class="col-md-3">
											<article>
												<div class="blog-image">
													<img class="img-responsive" src="<%= asset_path 'img3.jpg' %>" alt="" />
												</div>
												<div class="card-body blog-text">
													<div class="opacity-50">Posted on Feb 20 by <a href="#">Admin</a> | <a href="#">2 comments <i class="fa fa-comment-o"></i></a></div>
													<h3><a class="link-default" href="../../../html/pages/blog/post.html">Anim mollit</a></h3>
													<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
													<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
												</div>
											</article><!-- end /article -->
											<article>
												<div class="blog-image">
													<img class="img-responsive" src="<%= asset_path 'img4.jpg' %>" alt="" />
												</div>
												<div class="card-body blog-text">
													<div class="opacity-50">Posted on Feb 20 by <a href="#">Admin</a> | <a href="#">2 comments <i class="fa fa-comment-o"></i></a></div>
													<h3><a class="link-default" href="../../../html/pages/blog/post.html">Tempor incididunt elit</a></h3>
													<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
													<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
												</div>
											</article><!-- end /article -->
										</div>
										<div class="col-md-3">
											<article>
												<div class="card-body style-primary blog-text">
													<div class="opacity-50">Posted on Feb 20 by <a href="#">Admin</a> | <a href="#">2 comments <i class="fa fa-comment-o"></i></a></div>
													<h3><a class="link-default" href="../../../html/pages/blog/post.html">Exercitation ullamco</a></h3>
													<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
													<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
												</div>
												<div class="blog-image">
													<img class="img-responsive" src="<%= asset_path 'img5.jpg' %>" alt="" />
												</div>
											</article><!-- end /article -->
											<article>
												<div class="card-body blog-text">
													<div class="opacity-50">Posted on Feb 20 by <a href="#">Admin</a> | <a href="#">2 comments <i class="fa fa-comment-o"></i></a></div>
													<h3><a class="link-default" href="../../../html/pages/blog/post.html">Exercitation ullamco</a></h3>
													<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
													<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
												</div>
												<div class="card-body text-center style-default-dark">
													<h3><i class="fa fa-quote-left"></i> Some quote <i class="fa fa-quote-right"></i></h3>
												</div>
												<div class="card-body text-center card-body-darken style-default-dark">
													<h4><i class="fa fa-quote-left"></i> Another one for the books <i class="fa fa-quote-right"></i></h4>
												</div>
											</article><!-- end /article -->
										</div><!--end .col -->
										<div class="col-md-3">
											<article>
												<div class="blog-image">
													<img class="img-responsive" src="<%= asset_path 'img6.jpg' %>" alt="" />
												</div>
												<div class="card-body blog-text">
													<div class="opacity-50">Posted on Feb 20 by <a href="#">Admin</a> | <a href="#">2 comments <i class="fa fa-comment-o"></i></a></div>
													<h3><a class="link-default" href="../../../html/pages/blog/post.html">Exercitation ullamco</a></h3>
													<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
													<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
												</div>
											</article><!-- end /article -->
											<article>
												<div class="blog-image">
													<img class="img-responsive" src="<%= asset_path 'img7.jpg' %>" alt="" />
												</div>
												<div class="card-body blog-text style-primary-dark">
													<div class="opacity-50">Posted on Feb 20 by <a href="#">Admin</a> | <a href="#">2 comments <i class="fa fa-comment-o"></i></a></div>
													<h3><a class="link-default" href="../../../html/pages/blog/post.html">Exercitation ullamco</a></h3>
													<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
													<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
													<p>Excepteur sint occaecat cupidatat non proide</p>
												</div>
											</article><!-- end /article -->
										</div><!--end .col -->
									</div><!--end .row -->
								</div><!--end .card -->
								<!-- END BLOG MASONRY -->

							</div><!--end .col -->
						</div><!--end .row -->

						<!-- BEGIN PAGINATION -->
						<div class="row">
							<div class="col-lg-12 text-center">
								<ul class="pagination pagination-lg">
									<li class="disabled"><a href="#">«</a></li>
									<li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
									<li><a href="#">2</a></li>
									<li><a href="#">3</a></li>
									<li><a href="#">4</a></li>
									<li><a href="#">5</a></li>
									<li><a href="#">»</a></li>
								</ul>
							</div><!--end .col -->
						</div><!--end .row -->
						<!-- END PAGINATION -->

					</div><!--end .section-body -->
				</section>
			</div><!--end #content-->
			<!-- END CONTENT -->

app/views/dashboard/index.html.erb
<%if current_user %>
<!-- BEGIN CONTENT-->
<div id="content">
  <section>
    <div class="section-body">
      <div class="row">
        <p id="notice"><%= notice %></p>

        <div class="page-header">
          <h1><%= link_to "Postea tu canal", new_message_path, class:"btn btn-success" %></h1>
        </div>

        

        <% @messages.each do |message| %>

        <!-- BEGIN ALERT - REVENUE -->
        <div class="col-md-12 col-sm-6">
          <div class="card">
            <div class="card-body no-padding">
              <div class="alert alert-callout alert-info no-margin">
               <!-- <strong class="pull-right text-success text-lg"><i class="fa fa-line-chart" aria-hidden="true"></i></strong>-->

               <strong class="text-xl"><h1>
                 ¿En que piensas?
                 
               </h1></strong><br/>

               <strong class="text-xl">

                <p>
                  <%= message.descripcion %>
                </p>
              </strong>
              <br/> 

              <div style="text-align: center;"><span class="opacity-50">

               <!-- <i class="fa fa-eye"><%= link_to 'Ver', message %></i>-->
                &nbsp;&nbsp;
                <i class="fa fa-pencil"> <%= link_to 'Edit', edit_message_path(message) %></i>
                &nbsp;&nbsp;
                
                <i class="fa fa-trash"> <%= link_to 'Eliminar', message, method: :delete, data: { confirm: '¿Seguro que desea eliminar el post?' } %></i> 
                &nbsp;&nbsp;

                <a href="#">Compartir<i class="fa fa-share-alt"></i></a>
                &nbsp;&nbsp;
                <a href="#">Adjuntar<i class="fa fa-picture-o"></i></a>
              </span>
              &nbsp;&nbsp;
              
              <%= link_to like_message_path(message), method:     :put do %>

              <i class="fa fa-thumbs-o-up"><span>
                <%= message.get_upvotes.size %>
              </span></i>


              &nbsp;&nbsp;
              <%end%>
              

            </div>
            <div>
              <%= commontator_thread(message) %>
            </div>
          </div>
        </div><!--end .card-body -->
        
      </div><!--end .card -->
    </div><!--end .col -->
    <!-- END ALERT - REVENUE -->     
    
    
    <% end %>
    

    <br>


    


    
    
  </div>
</div>
</section>
</div>
<!-- BEGIN CONTENT-->  




<%end%>


<style>

  a:hover{
    color: rgb(43, 184, 200);
    text-decoration: none;

  }

</style>

app/views/dashboard/profile.html.erb
<!-- BEGIN CONTENT-->
			<div id="content">

				<!-- BEGIN PROFILE HEADER -->
				<section class="full-bleed">
					<div class="section-body style-default-dark force-padding text-shadow">
						<div class="img-backdrop" style="background-image: url('<%= asset_path 'profilebg.jpg' %>')"></div>
						<div class="overlay overlay-shade-top stick-top-left height-3"></div>
						<div class="row">
							<div class="col-md-3 col-xs-5">
								<img class="img-circle border-white border-xl img-responsive auto-width" src="<%= asset_path 'perfil.jpg' %>" style="width: 140px; height: 140px;" alt="" />
								<h3><%=current_user.email%><br/><small style="color:white;">Administrador</small></h3>
							</div><!--end .col -->
							<div class="col-md-9 col-xs-7">
								<div class="width-3 text-center pull-right">
									<strong class="text-xl">643</strong><br/>
									<span class="text-light opacity-75">followers</span>
								</div>
								<div class="width-3 text-center pull-right">
									<strong class="text-xl">108</strong><br/>
									<span class="text-light opacity-75">following</span>
								</div>
							</div><!--end .col -->
						</div><!--end .row -->
						<div class="overlay overlay-shade-bottom stick-bottom-left force-padding text-right">
							<a class="btn btn-icon-toggle" data-toggle="tooltip" data-placement="top" data-original-title="Contact me"><i class="fa fa-envelope"></i></a>
							<a class="btn btn-icon-toggle" data-toggle="tooltip" data-placement="top" data-original-title="Follow me"><i class="fa fa-twitter"></i></a>
							<a class="btn btn-icon-toggle" data-toggle="tooltip" data-placement="top" data-original-title="Personal info"><i class="fa fa-facebook"></i></a>
						</div>
					</div><!--end .section-body -->
				</section>
				<!-- END PROFILE HEADER  -->

				<section>
					<div class="section-body no-margin">
						<div class="row">
							<div class="col-md-8">
								<h2>Timeline</h2>

								<!-- BEGIN ENTER MESSAGE -->
								<form class="form">
									<div class="card no-margin">
										<div class="card-body">
											<div class="form-group floating-label">
												<textarea name="status" id="status" class="form-control autosize" rows="1"></textarea>
												<label for="status">What's on your mind?</label>
											</div>
										</div><!--end .card-body -->
										<div class="card-actionbar">
											<div class="card-actionbar-row">
												<div class="pull-left">
													<a class="btn btn-icon-toggle ink-reaction btn-default"><i class="fa fa-camera" aria-hidden="true"></i></a>
													<a class="btn btn-icon-toggle ink-reaction btn-default"><i class="fa fa-map-marker" aria-hidden="true"></i></a>
													<a class="btn btn-icon-toggle ink-reaction btn-default"><i class="fa fa-paperclip" aria-hidden="true"></i></a>
												</div>
												<a href="javascript:void(0);" class="btn btn-flat btn-accent ink-reaction">Post</a>
											</div><!--end .card-actionbar-row -->
										</div><!--end .card-actionbar -->
									</div><!--end .card -->
								</form>

								<!-- BEGIN ENTER MESSAGE -->

								<!-- BEGIN MESSAGE ACTIVITY -->
								<div class="tab-pane" id="activity">
									<ul class="timeline collapse-lg timeline-hairline">
										<li class="timeline-inverted">
											<div class="timeline-circ circ-xl style-primary"><i class="fa fa-calendar" aria-hidden="true"></i></div>
											<div class="timeline-entry">
												<div class="card style-default-light">
													<div class="card-body small-padding">
														<span class="text-medium">Received a <a class="text-primary" href="../../html/mail/inbox.html">message</a> from <span class="text-primary">Ann Lauren</span></span><br/>
														<span class="opacity-50">
															Saturday, Oktober 18, 2014
														</span>
													</div>
												</div>
											</div><!--end .timeline-entry -->
										</li>
										<li>
											<div class="timeline-circ circ-xl style-primary-dark"><i class="fa fa-clock-o" aria-hidden="true"></i></i></div>
											<div class="timeline-entry">
												<div class="card style-default-light">
													<div class="card-body small-padding">
														<p>
															<span class="text-medium">User login at <span class="text-primary">8:15 pm</span></span><br/>
															<span class="opacity-50">
																Saturday, August 2, 2014
															</span>
														</p>
														Check out my new location.
													</div>
												</div>
											</div><!--end .timeline-entry -->
										</li>
										<li>
											<div class="timeline-circ circ-xl style-primary"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
											<div class="timeline-entry">
												<div class="card style-default-light">
													<div class="card-body small-padding">
														<img class="img-circle img-responsive pull-left width-1" src="<%= asset_path 'avatar2.jpg' %>" alt="" />
														<span class="text-medium">Meeting in the <span class="text-primary">conference room</span></span><br/>
														<span class="opacity-50">
															Saturday, Juli 29, 2014
														</span>
													</div>
													<div class="card-body">
														<p><em>Walked all the way home...</em></p>
														<img class="img-responsive" src="<%= asset_path 'img14.jpg' %>" alt="" />
													</div>
												</div>
											</div><!--end .timeline-entry -->
										</li>
									</ul>
								</div><!--end #activity -->
							</div><!--end .col -->
							<!-- END MESSAGE ACTIVITY -->

							<!-- BEGIN PROFILE MENUBAR -->
							<div class="col-lg-offset-1 col-lg-3 col-md-4">
								<div class="card card-underline style-default-dark">
									<div class="card-head">
										<header class="opacity-75"><small>Friends</small></header>
										<div class="tools">
											<form class="navbar-search" role="search">
												<div class="form-group">
													<input type="text" class="form-control" name="friendSearch" placeholder="Enter your keyword">
												</div>
												<button type="submit" class="btn btn-icon-toggle ink-reaction"><i class="fa fa-search"></i></button>
											</form>
										</div><!--end .tools -->
									</div><!--end .card-head -->
									<div class="card-body no-padding">
										<ul class="list">
											<li class="tile">
												<a class="tile-content ink-reaction" href="#2">
													<div class="tile-icon">
														<img src="<%= asset_path 'avatar2.jpg' %>" alt="" />
													</div>
													<div class="tile-text">Abbey Johnson<small>Lorem ipsum dolor sit amet, consectetur adipisicing</small></div>
												</a>
											</li>
											<li class="tile">
												<a class="tile-content ink-reaction">
													<div class="tile-icon">
														<img src="<%= asset_path 'avatar4.jpg' %>" alt="" />
													</div>
													<div class="tile-text">Alex Nelson<small>Proin nonummy, lacus eget pulvinar lacinia</small></div>
												</a>
											</li>
											<li class="tile">
												<a class="tile-content ink-reaction">
													<div class="tile-icon">
														<img src="<%= asset_path 'avatar2.jpg' %>" alt="" />
													</div>
													<div class="tile-text">Mary Peterson<small>Nulla gravida orci a odio</small></div>
												</a>
											</li>
											<li class="tile">
												<a class="tile-content ink-reaction">
													<div class="tile-icon">
														<img src="<%= asset_path 'avatar7.jpg' %>" alt="" />
													</div>
													<div class="tile-text">Trevor Hanson<small>Nullam varius, turpis et commodo pharetra</small></div>
												</a>
											</li>
										</ul>
									</div><!--end .card-body -->
								</div><!--end .card -->
								<div class="card card-underline style-default-dark">
									<div class="card-head">
										<header class="opacity-75"><small>Personal info</small></header>
										<div class="tools">
											<a class="btn btn-icon-toggle ink-reaction"><i class="md md-edit"></i></a>
										</div><!--end .tools -->
									</div><!--end .card-head -->
									<div class="card-body no-padding">
										<ul class="list">
											<li class="tile">
												<a class="tile-content ink-reaction">
													<div class="tile-icon">
														<i class="fa fa-map-marker" aria-hidden="true"></i>


													</div>
													<div class="tile-text">
														621 Johnson Ave, Suite 600
														<small>Street</small>
													</div>
												</a>
											</li>
											<li class="tile">
												<a class="tile-content ink-reaction">
													<div class="tile-icon"></div>
													<div class="tile-text">
														San Francisco, CA 54321
														<small>City</small>
													</div>
												</a>
											</li>
											<li class="divider-inset"></li>
											<li class="tile">
												<a class="tile-content ink-reaction">
													<div class="tile-icon">
														<i class="fa fa-phone" aria-hidden="true"></i>

													</div>
													<div class="tile-text">
														(123) 456-7890
														<small>Mobile</small>
													</div>
												</a>
											</li>
											<li class="tile">
												<a class="tile-content ink-reaction">
													<div class="tile-icon"></div>
													<div class="tile-text">
														(323) 555-6789
														<small>Work</small>
													</div>
												</a>
											</li>
										</ul>
									</div><!--end .card-body -->
								</div><!--end .card -->
							</div><!--end .col -->
							<!-- END PROFILE MENUBAR -->

						</div><!--end .row -->
					</div><!--end .section-body -->
				</section>
			</div><!--end #content-->
			<!-- END CONTENT -->