config/routes.rb
Rails.application.routes.draw do
  
  
  resources :links
  resources :messages do
    member do
      put "like" => "messages#upvote"
      put "unlike" => "messages#downvote"
    end
  end
  mount Commontator::Engine => '/commontator'
  resources :followers
  resources :followeds
  resources :canals
  resources :preferencia

  resources :usuarios, as: :users, only: [:show,:update]  #esto es una prueba, que si funciono 

  resources :relationships, only: [:create,:update,:index]

 
  resources :editlandings
  resources :pais
  get '/index', to: 'landing#index'
  get '/informacion', to: 'landing#informacion'
  get '/perfil', to: 'dashboard#profile'


  #administrar landing 
  get '/landingpage', to: 'editlandings#index'
  #administrar landing



  root 'dashboard#index'
   
  devise_for :users, controllers: { sessions: "users/sessions", :registrations => "users/registrations", :confirmations => "users/confirmations" }
   match '/users/:id/canals/:id', controller: 'canals', action: 'update', via: 'post'
          
  resources :users do
     resources :favoritos
  	 resources :canals do

       

     end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/asd.rb
class Asd < ApplicationRecord
end

app/models/canal.rb
class Canal < ApplicationRecord
	belongs_to :user
	has_many :messages
end

app/models/editlanding.rb
class Editlanding < ApplicationRecord
	dragonfly_accessor :banner
	dragonfly_accessor :imagenseccion2
	dragonfly_accessor :bannernewsletter
	
end

app/models/favorito.rb
class Favorito < ApplicationRecord
	belongs_to :user
	has_one :preferencium
end

app/models/followed.rb
class Followed < ApplicationRecord
end

app/models/follower.rb
class Follower < ApplicationRecord
end

app/models/link.rb
class Link < ApplicationRecord
	acts_as_commontable
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	belongs_to :canal
	dragonfly_accessor :archivo
	acts_as_votable
	acts_as_commontable
end

app/models/pai.rb
class Pai < ApplicationRecord
end

app/models/preferencium.rb
class Preferencium < ApplicationRecord
	has_one:favorito
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	include AASM

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, uniqueness: {scope: :followed_id}

  #validates :follower, presence: true
  #validates :followed, presence: true

  def self.relations?(follower,followed)
  	Relationship.where(follower:follower,followed:followed)
  				.or(Relationship.where(follower:followed,followed:follower))
  				.any?
  end

  def self.pending_for_user(follower)
  	Relationship.pending.where(followed: follower)
  end

	aasm column: "status" do 
	 	state :pending
	 	state :active, initial: true
	 	state :denied

	 	event :accepted do
	 		transitions from: [:pending], to: [:active]
	 	end

	 	event :rejected do
	 		transitions from: [:pending,:active], to: [:denied]
	 	end
	 end
end

app/models/user.rb
 require "httparty"
 require "json"
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 
  include HTTParty
 acts_as_commontator
 acts_as_voter

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  dragonfly_accessor :fotoperfil
  dragonfly_accessor :portada

  has_many :canals
  has_many :messages
  has_many :favoritos
 
  has_many :relationships
#  has_many :active_relationships, class_name:  "relationship",
#                                  foreign_key: "follower_id",
 #                                 dependent:   :destroy

 # has_many :passive_relationships, class_name:  "relationship",
  #                                 foreign_key: "followed_id",
   #                                dependent:   :destroy
  
  #has_many :following, through: :active_relationships, source: :followed

  #has_many :followers, through: :passive_relationships, source: :follower
  def follow?(followed)
    Relationship.relations?(self,followed)
  end


    # Follows a user.
  #def follow(other_user)
   # following << other_user
  #end

  # Unfollows a user.
  #def unfollow(other_user)
   # following.delete(other_user)
  #end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
    def self.abc

  	@json = get("http://localhost:4040/graduateds.json")
  	@json = @json.to_json
  	@parsed_json = ActiveSupport::JSON.decode(@json)
  	@no = @parsed_json

  	return @no

  end

end

app/controllers/preferencia_controller.rb
class PreferenciaController < ApplicationController
  before_action :set_preferencium, only: [:show, :edit, :update, :destroy]

  # GET /preferencia
  # GET /preferencia.json
  def index
    @preferencia = Preferencium.all
  end

  # GET /preferencia/1
  # GET /preferencia/1.json
  def show
  end

  # GET /preferencia/new
  def new
    @preferencium = Preferencium.new
    
  end

  # GET /preferencia/1/edit
  def edit
  end

  # POST /preferencia
  # POST /preferencia.json
  def create
    @preferencium = Preferencium.new(preferencium_params)
    
    respond_to do |format|
      if @preferencium.save
        format.html { redirect_to '/preferencia', notice: 'Preferencium was successfully created.' }
        format.json { render :show, status: :created, location: @preferencium }
      else
        format.html { render :new }
        format.json { render json: @preferencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preferencia/1
  # PATCH/PUT /preferencia/1.json
  def update
    respond_to do |format|
      if @preferencium.update(preferencium_params)
        format.html { redirect_to @preferencium, notice: 'Preferencium was successfully updated.' }
        format.json { render :show, status: :ok, location: @preferencium }
      else
        format.html { render :edit }
        format.json { render json: @preferencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preferencia/1
  # DELETE /preferencia/1.json
  def destroy
    @preferencium.destroy
    respond_to do |format|
      format.html { redirect_to preferencia_url, notice: 'Preferencium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preferencium
      @preferencium = Preferencium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preferencium_params
      params.require(:preferencium).permit(:nombre)
    end
end

app/helpers/canals_helper.rb
module CanalsHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pais_helper.rb
module PaisHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/preferencia_helper.rb
module PreferenciaHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/preferencia/_form.html.erb
<!-- BEGIN CONTENT-->
      <div id="content">
        <section>
          <div class="section-body">
            <div class="row">
       <div class="col-lg-6">  
<%= form_for(preferencium) do |f| %>
  <% if preferencium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(preferencium.errors.count, "error") %> prohibited this preferencium from being saved:</h2>

      <ul>
      <% preferencium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field" style="margin-left: auto;margin-right: auto;display: table;">
                <div data-icon="&#xe563;" class="prefix"></div>

  <div class="estilo2"><%= f.label :nombre %>:</span>
                <%= f.text_field :nombre, class: "validate estilo" %>

  </div>

    
<br>
<div style="margin-left: auto;margin-right: auto;display: table;">
   <button class="btn waves-effect waves-light actions-submit" type="submit" name="action" id="actions-form-submit" style="background: #2bb8c9;">Guardar</button>
</div>
<% end %>

           </div>
                
</div>
</div>
</section>
</div> 
<!-- BEGIN CONTENT-->  

<style>
  
.estilo{
  border-bottom: 1px solid rgb(43, 184, 201);
border-top: none;
background-color: transparent;
border-left: none;
border-right: none;
}

.estilo2{
font-size: 18px;


}

</style>

app/views/preferencia/edit.html.erb
<!-- BEGIN CONTENT-->
      <div id="content">
        <section>
          <div class="section-body">
            <div class="row">
			
			<h1 style="margin-left: auto;margin-right: auto;display: table;">Editar nombre de la preferencia</h1>
<div class="col-md-12 col-sm-6">
                <div class="card">
                  <div class="card-body no-padding">
                    <div class="alert alert-callout alert-info no-margin">

<%= render 'form', preferencium: @preferencium %>

<div style="margin-left: auto;margin-right: auto;display: table;">

<%= link_to 'Ver', @preferencium %> |
<%= link_to 'Volver', preferencia_path %>

</div>


			  </div><!--end .card-body -->
                </div><!--end .card -->
              </div><!--end .col -->
              <!-- END ALERT - REVENUE -->  
</div>
			</div>
           </div>
          </section>
        </div>
<!-- BEGIN CONTENT-->

app/views/preferencia/index.html.erb
<!-- BEGIN CONTENT-->
      <div id="content">
        <section>
          <div class="section-body">
            <div class="row">
              <p id="notice"><%= notice %></p>

                <div class="page-header">
                <h1><%= link_to "Agregar preferencia", new_preferencium_path, class:"btn btn-success" %></h1>
                </div>
            
                <!-- Lista -->


                      <tbody>
                        <% @preferencia.each do |preferencium| %>
                          <tr>
                            <td><%= preferencium.nombre %></td>
                     <div style="text-align: center;"><span class="opacity-50">
        
                    <i class="fa fa-eye"><%= link_to 'Ver', preferencium %></i>
                    &nbsp;&nbsp;
                    <i class="fa fa-pencil"> <%= link_to 'Edit', edit_preferencium_path(preferencium) %></i>
                    &nbsp;&nbsp;
           
                  <i class="fa fa-trash"> <%= link_to 'Eliminar', preferencium, method: :delete, data: { confirm: '¿Seguro que desea eliminar?' } %></i> 
                  &nbsp;&nbsp; 
          </span>
          </div>
                          </tr>
                        <% end %>
                      </tbody>
                
              
            </div>
          </div>
        </section>
      </div>
<!-- BEGIN CONTENT-->

app/views/preferencia/new.html.erb
<!-- BEGIN CONTENT-->
      <div id="content">
        <section>
          <div class="section-body">
            <div class="row">
			<h1 style="margin-left: auto;margin-right: auto;display: table;">Añadir preferencia</h1>

<div class="col-md-12 col-sm-6">
                <div class="card">
                  <div class="card-body no-padding">
                    <div class="alert alert-callout alert-info no-margin">

<%= render 'form', preferencium: @preferencium %>

<div style="margin-left: auto;margin-right: auto;display: table;"> <%= link_to 'Volver', preferencia_path %>



				</div><!--end .card-body -->
                </div><!--end .card -->
              </div><!--end .col -->
              <!-- END ALERT - REVENUE -->  

              </div>
           </div>
          </section>
        </div>

app/views/preferencia/show.html.erb
<!-- BEGIN CONTENT-->
      <div id="content">
        <section>
          <div class="section-body">
            <div class="row">
              <p id="notice"><%= notice %></p>

<p id="notice"><%= notice %></p>

 <!-- BEGIN ALERT - REVENUE -->
              <div class="col-md-5 col-sm-6">
                <div class="card">
                  <div class="card-body no-padding">
                    <div class="alert alert-callout alert-info no-margin">
                     <!-- <strong class="pull-right text-success text-lg"><i class="fa fa-line-chart" aria-hidden="true"></i></strong>-->

                      <strong class="text-xl"><h1>
  

<p>
  <strong>Nombre:</strong>
  <strong class="text-xl"><p>
  <%= @preferencium.nombre %>
</p></strong><br/>
	 <span class="opacity-50">

          <i class="fa fa-pencil"><%= link_to 'Editar',edit_preferencium_path(@preferencium) %></i>
           &nbsp;&nbsp;

          <i class="fa fa-reply"><%= link_to 'Back', preferencia_path %></i>
           &nbsp;&nbsp;
          </span>
                      
                    </div>
                  </div><!--end .card-body -->
                </div><!--end .card -->
              </div><!--end .col -->
              <!-- END ALERT - REVENUE -->
</div>
</div>
</section>
</div>
<!-- BEGIN CONTENT-->  