config/routes.rb
Rails.application.routes.draw do
  
  
  resources :links
  resources :messages do
    member do
      put "like" => "messages#upvote"
      put "unlike" => "messages#downvote"
    end
  end
  mount Commontator::Engine => '/commontator'
  resources :followers
  resources :followeds
  resources :canals
  resources :preferencia

  resources :usuarios, as: :users, only: [:show,:update]  #esto es una prueba, que si funciono 

  resources :relationships, only: [:create,:update,:index]

 
  resources :editlandings
  resources :pais
  get '/index', to: 'landing#index'
  get '/informacion', to: 'landing#informacion'
  get '/perfil', to: 'dashboard#profile'


  #administrar landing 
  get '/landingpage', to: 'editlandings#index'
  #administrar landing



  root 'dashboard#index'
   
  devise_for :users, controllers: { sessions: "users/sessions", :registrations => "users/registrations", :confirmations => "users/confirmations" }
   match '/users/:id/canals/:id', controller: 'canals', action: 'update', via: 'post'
          
  resources :users do
     resources :favoritos
  	 resources :canals do

       

     end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/asd.rb
class Asd < ApplicationRecord
end

app/models/canal.rb
class Canal < ApplicationRecord
	belongs_to :user
	has_many :messages
end

app/models/editlanding.rb
class Editlanding < ApplicationRecord
	dragonfly_accessor :banner
	dragonfly_accessor :imagenseccion2
	dragonfly_accessor :bannernewsletter
	
end

app/models/favorito.rb
class Favorito < ApplicationRecord
	belongs_to :user
	has_one :preferencium
end

app/models/followed.rb
class Followed < ApplicationRecord
end

app/models/follower.rb
class Follower < ApplicationRecord
end

app/models/link.rb
class Link < ApplicationRecord
	acts_as_commontable
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	belongs_to :canal
	dragonfly_accessor :archivo
	acts_as_votable
	acts_as_commontable
end

app/models/pai.rb
class Pai < ApplicationRecord
end

app/models/preferencium.rb
class Preferencium < ApplicationRecord
	has_one:favorito
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	include AASM

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, uniqueness: {scope: :followed_id}

  #validates :follower, presence: true
  #validates :followed, presence: true

  def self.relations?(follower,followed)
  	Relationship.where(follower:follower,followed:followed)
  				.or(Relationship.where(follower:followed,followed:follower))
  				.any?
  end

  def self.pending_for_user(follower)
  	Relationship.pending.where(followed: follower)
  end

	aasm column: "status" do 
	 	state :pending
	 	state :active, initial: true
	 	state :denied

	 	event :accepted do
	 		transitions from: [:pending], to: [:active]
	 	end

	 	event :rejected do
	 		transitions from: [:pending,:active], to: [:denied]
	 	end
	 end
end

app/models/user.rb
 require "httparty"
 require "json"
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 
  include HTTParty
 acts_as_commontator
 acts_as_voter

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  dragonfly_accessor :fotoperfil
  dragonfly_accessor :portada

  has_many :canals
  has_many :messages
  has_many :favoritos
 
  has_many :relationships
#  has_many :active_relationships, class_name:  "relationship",
#                                  foreign_key: "follower_id",
 #                                 dependent:   :destroy

 # has_many :passive_relationships, class_name:  "relationship",
  #                                 foreign_key: "followed_id",
   #                                dependent:   :destroy
  
  #has_many :following, through: :active_relationships, source: :followed

  #has_many :followers, through: :passive_relationships, source: :follower
  def follow?(followed)
    Relationship.relations?(self,followed)
  end


    # Follows a user.
  #def follow(other_user)
   # following << other_user
  #end

  # Unfollows a user.
  #def unfollow(other_user)
   # following.delete(other_user)
  #end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
    def self.abc

  	@json = get("http://localhost:4040/graduateds.json")
  	@json = @json.to_json
  	@parsed_json = ActiveSupport::JSON.decode(@json)
  	@no = @parsed_json

  	return @no

  end

end

app/controllers/favoritos_controller.rb
class FavoritosController < ApplicationController
  before_action :set_favorito, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /favoritos
  # GET /favoritos.json
  def index
    @favoritos = Favorito.where(user_id: current_user.id)
  end

  # GET /favoritos/1
  # GET /favoritos/1.json
  def show
  end

  # GET /favoritos/new
  def new
    @favorito = Favorito.new
    
  end

  # GET /favoritos/1/edit
  def edit
  end

  # POST /favoritos
  # POST /favoritos.json
  def create
    @favorito = Favorito.new(favorito_params)

    respond_to do |format|
      if @favorito.save
        format.html { redirect_to '/users/'+current_user.id.to_s+'/favoritos', notice: 'Favorito was successfully created.' }
        format.json { render :show, status: :created, location: @favorito }
      else
        format.html { render :new }
        format.json { render json: @favorito.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favoritos/1
  # PATCH/PUT /favoritos/1.json
  def update
    respond_to do |format|
      if @favorito.update(favorito_params)
        format.html { redirect_to @favorito, notice: 'Favorito was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorito }
      else
        format.html { render :edit }
        format.json { render json: @favorito.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favoritos/1
  # DELETE /favoritos/1.json
  def destroy
    @favorito.destroy
    respond_to do |format|
      format.html { redirect_to favoritos_url, notice: 'Favorito was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorito
      @favorito = Favorito.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorito_params
      params.require(:favorito).permit(:user_id, :preferencia_id)
    end
end

app/helpers/canals_helper.rb
module CanalsHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/helpers/favoritos_helper.rb
module FavoritosHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pais_helper.rb
module PaisHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favoritos/_form.html.erb
<%= form_for(favorito) do |f| %>
  <% if favorito.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favorito.errors.count, "error") %> prohibited this favorito from being saved:</h2>

      <ul>
      <% favorito.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :preferencia_id %>
    <%= f.number_field :preferencia_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favoritos/edit.html.erb
<h1>Editing Favorito</h1>

<%= render 'form', favorito: @favorito %>

<%= link_to 'Show', @favorito %> |
<%= link_to 'Back', favoritos_path %>

app/views/favoritos/index.html.erb
<!-- BEGIN CONTENT-->
  <div id="content">
    <section>
      <div class="section-body">

        <div class="row">

              <!-- Crear nueva -->
              <a style="margin-left: 10px; color:#2BB8C8;" href="/users/<%=current_user.id%>/favoritos/new" class="btn btn-flat btn-primary ink-reaction"> <i style="margin-right: 5px;" class="fa fa-plus-square" aria-hidden="true"></i>
Añadir nueva preferencia a mi perfil</a>

              <!-- Crear nueva -->
          
        </div>

        <div class="row" style="margin-top: 20px;">

        

            <div class="col-lg-12">

                  <div class="card">
                  <div class="card-head style-primary">
                      <header>Mis Preferencias</header>
                  </div>

                  <div class="card-body">

                  <%@favoritos.each do |f|%>

                  <!-- BEGIN ALERT - REVENUE -->
              <div class="col-md-4 col-sm-6">
                <div class="card">
                  <div class="card-body no-padding">
                    <div class="alert alert-callout alert-warning no-margin">
                      <strong class="pull-right text-warning text-lg"><i class="fa fa-star" aria-hidden="true"></i></strong>
                     <strong class="text-xl"><%= Preferencium.find(f.preferencia_id).nombre%></strong><br/> 
                      <span class="opacity-50">Preferencia</span>
                      
                    </div>
                  </div><!--end .card-body -->
                </div><!--end .card -->
              </div><!--end .col -->
              <!-- END ALERT - REVENUE -->

                  <%end%>

                  </div>

                  </div>

            </div>
        </div>
      </div>
    </section>
  </div>
<!-- BEGIN CONTENT -->

app/views/favoritos/new.html.erb
<!-- estilos -->
		<link type="text/css" rel="stylesheet" href="https://kapitalizalo.tk/admin/libs/bootstrap-datepicker/datepicker3.css" />


		<!-- BEGIN STYLESHEETS -->
		<link href='http://fonts.googleapis.com/css?family=Roboto:300italic,400italic,300,400,500,700,900' rel='stylesheet' type='text/css'/>
		
	
	
		<link type="text/css" rel="stylesheet" href="https://kapitalizalo.tk/admin/libs/select2/select2.css?1424887856" />
		<link type="text/css" rel="stylesheet" href="https://kapitalizalo.tk/admin/libs/multi-select/multi-select.css?1424887857" />
		<link type="text/css" rel="stylesheet" href="https://kapitalizalo.tk/admin/libs/bootstrap-datepicker/datepicker3.css?1424887858" />
		<link type="text/css" rel="stylesheet" href="https://kapitalizalo.tk/admin/libs/libs/jquery-ui/jquery-ui-theme.css?1423393666" />
		<link type="text/css" rel="stylesheet" href="https://kapitalizalo.tk/admin/libs/bootstrap-colorpicker/bootstrap-colorpicker.css?1424887860" />
		<link type="text/css" rel="stylesheet" href="https://kapitalizalo.tk/admin/libs/bootstrap-tagsinput/bootstrap-tagsinput.css?1424887862" />
		<link type="text/css" rel="stylesheet" href="https://kapitalizalo.tk/admin/libs/typeahead/typeahead.css?1424887863" />
		<link type="text/css" rel="stylesheet" href="https://kapitalizalo.tk/admin/libs/libs/dropzone/dropzone-theme.css?1424887864" />
		<!-- END STYLESHEETS -->
<!-- estilos -->



<!-- BEGIN CONTENT-->
  <div id="content">
    <section>
      <div class="section-body">

        <div class="row">


            <div class="col-lg-12">

            	  <!-- form -->

				 <form class="smart-form" id="new_trackrecord"  action="/users/<%=current_user.id%>/favoritos" accept-charset="UTF-8" method="post" enctype="multipart/form-data">

                  <div class="card">
                  <div class="card-head style-primary">
                      <header>Nueva Preferencia</header>
                  </div>

                  <div class="card-body">

                  	 <!-- favoritos -->
                              
                              <div class="col-lg-12">
                                 

                                    <select id="select-favorito" class="form-control select2-list">
                                    	
										<option value="0">Selecciona una preferencia</option>
                    
                  <%Preferencium.all.each do |p|%>
                    <option value="<%=p.id%>"><%=p.nombre%>

										</option>
                                    	<%end%>

                                    	
                                    </select>
                                    <label for="">Preferencias Disponibles</label>
                                    
                                  
                              </div>

                              <input type="hidden" name="favorito[preferencia_id]" id="favorito_preferencia_id">

                              <input type="hidden" name="favorito[user_id]" id="favorito_user_id" value="<%=current_user.id%>"> 

                          <!-- favoritoas -->

                          <!-- Boton -->

                          <div class="col-lg-12">
                          	
							<!-- Boton Guardar -->

										<div class="card-actionbar">
											<div class="card-actionbar-row">
												<button type="submit" class="btn btn-flat btn-primary ink-reaction">Agregar</button>
											</div>
										</div>

										<!-- Boton Guardar -->

                          </div>

                          <!-- Boton -->

                  </div>
                  </div>

                  </form>


                  <!-- form -->
            </div>

        </div>
      </div>
    </section>
  </div>
<!-- BEGIN CONTENT -->
<script>
	$("#new_favorito").addClass("form");
</script>
<script src="https://kapitalizalo.tk/admin/js/libs/jquery/jquery-1.11.2.min.js"></script>
<script src="https://kapitalizalo.tk/admin/js/libs/bootstrap-datepicker/bootstrap-datepicker.js"></script>
<script src="https://kapitalizalo.tk/admin/js/libs/select2/select2.min.js"></script>
<script src="https://kapitalizalo.tk/admin/js/core/demo/DemoFormComponents.js"></script>

<script>
	/* Tipo de Track */
	$("#select-favorito").change(function() {
	$( "#favorito_preferencia_id" ).val($( "#select-favorito :selected" ).val());
	});
	/* Tipo de Track */
</script>

app/views/favoritos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Preferencia:</strong>
  <%= @favorito.preferencia_id %>
</p>

<%= link_to 'Edit', edit_favorito_path(@favorito) %> |
<%= link_to 'Back', favoritos_path %>